### ISSUE TITLE
iOS builds failing to initialize client dictionary

### ISSUE THREAD

**Issue by DavidFair123** [RiptideNetworking/Riptide#44] opened 2022-05-30 03:50 UTC
Connect method in client passes Assembly.GetCallingAssembly(). On PC builds this returns Assembly-CSharp - which causes no issues with dictionary initialization. However, on iOS this returns UnityEngine.CoreModule and no methods are found in this assembly for initializing the client dictionary.

**Comment by tom-weiland** [comment] 2022-07-02 03:38
@DavidFair123 I think some of the recent commits *should* have fixed your issue, but would you be able to confirm whether or not that is actually the case? I work on a Windows PC so testing on iOS is somewhat cumbersome for me.

You can install the latest code via the Unity Package Manager from `https://github.com/tom-weiland/RiptideNetworking.git?path=/Unity/Packages/Core`, or grab the dll from one of the demos.

**Comment by tom-weiland** [comment] 2022-10-06 23:27
Closing this as it should've been fixed by past commits, I've been unable to reproduce the issue, and there have been no more responses.

**Closed by tom-weiland** 2022-10-06 23:27 UTC
Labels: Bug
